name: restaurant_tour
description: Flutter developer coding challenge starter project.

publish_to: 'none'

version: 1.0.0+1


environment:
  sdk: ">=3.1.0 <4.0.0"
  flutter: ">=3.19.6"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  firebase_crashlytics: ^3.5.7
  firebase_core: ^2.32.0
  flutter_secure_storage: ^9.2.4
  shared_preferences: ^2.2.3
  flutter_bloc: ^9.0.0
  dio: ^5.8.0+1
  get_it: ^8.0.3
  go_router: ^14.8.1
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  crypto: ^3.0.3

dependency_overrides:
  watcher: ^1.0.0
  file: ^7.0.0
  pub_semver: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.3.0
  json_serializable: ^6.8.0

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/placeholder-image.jpg
  fonts:
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora/Lora-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lora/Lora-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lora/Lora-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lora/Lora-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans/OpenSans-Regular.ttf
          weight: 400
        - asset: assets/fonts/OpenSans/OpenSans-Italic.ttf
          style: italic
        - asset: assets/fonts/OpenSans/OpenSans-SemiBold.ttf
          weight: 600
        
